# Site settings
title: dpitt.me
name: dan pittman
username: danielscottt
email: danielscottt@gmail.com
description: a guy who programs. sometimes.
baseurl: ''
url: "http://dpitt.me"
highlighter: pygments

# Build settings
markdown: kramdown
permalink: pretty
